# Generated by Django 5.2 on 2025-05-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='primary_button_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='primary_button_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='secondary_button_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='secondary_button_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
